# ===================================
# CONFIGURAÇÕES GERAIS DA FERRAMENTA
# ===================================

# Informações da ferramenta
tool:
    name: Prometheus
    version: 2.0
    author: Xzhyan
    description: >
        Ferramenta CLI para agilizar, automatizar tarefas
        e entregar funções específicas úteis.

# Atalhos e pastas, arquivos e outros
paths:
    codes: ./work